apiVersion: batch/v1
kind: Job
metadata:
  name: cat-config
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "cat {MOUNT_PATH}/{CONFIG_FILE}"
        resources:
          requests:
            cpu: "1"
            memory: "1024Mi"
        volumeMounts:
        - name: config
          mountPath: "{MOUNT_PATH}"
      volumes:
      - name: config
        configMap:
          name: config
      restartPolicy: Never
